### ISSUE TITLE
what happen to this? lol

### ISSUE THREAD

**Issue by iRinku** [Lutron/Cluffle#3]
It's hosted in other place or what?

**Comment by Lutron** [comment]
Didn't know this repo even existed anymore. The whole project was hosted for about 2 days, and then taken down, because honestly, the whole thing was one buggy and unperformant mess.
You can problem find the reddit thread on google, if I'm not mistaken there were one or two people hosting the page as well. Maybe those pages are still online. Otherwise, you can try to host it yourself, but you're probably better off writing your own version in that case.
